spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100000KB
      max-request-size: 100000KB
  datasource:
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    org:
      springframework:
        security: DEBUG