spring:
  datasource:
    url: jdbc:mysql://localhost:3306/obligaciones-financieras
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db.environments/dev
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: b0af945e-16b5-4d2b-9552-0000699bd970
          app-id-uri: 24ef7252-49ae-4771-b2a2-56f48ace5e3f