CREATE TABLE IF NOT EXISTS BANCOS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS CLASIFICACIONES_FISCALES (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS CLASIFICACIONES_FISCALES (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS CLASIFICACIONES_IMPUESTOS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS GRUPOS_RETENCIONES_IMPUESTOS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS PROYECTOS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 ESTADO VARCHAR(384) NOT NULL,
 CODIGO_GRUPO VARCHAR(384) NOT NULL,
 NOMBRE_GRUPO VARCHAR(384) NOT NULL,
 CODIGO_CONSOLIDADOR VARCHAR(384) NOT NULL,
 NOMBRE_CONSOLIDADOR VARCHAR(384) NOT NULL,
 CODIGO_PROYECTO VARCHAR(384) NOT NULL,
 NOMBRE_PROYECTO VARCHAR(384) NOT NULL,
 BANCO_CREDITO_CONSTRUCTOR VARCHAR(384) DEFAULT NULL,
 TIPO_FINANCIACION VARCHAR(384) DEFAULT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID),
 UNIQUE KEY CODIGO_PROYECTO (CODIGO_PROYECTO)
);

CREATE TABLE IF NOT EXISTS TASAS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 NOMBRE VARCHAR(384) NOT NULL,
 PERIODICIDAD VARCHAR(384) NOT NULL,
 TIPO_VALOR VARCHAR(384) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TIPOS_CLASIFICACIONES_FISCALES (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS TIPO_CUENTAS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS TIPO_ORGANIZACIONES_FISCALES (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS TIPO_TERCEROS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS UNIDADES_NEGOCIO (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  SIGLA VARCHAR(50) DEFAULT NULL,
  RAZON VARCHAR(50) DEFAULT NULL,
  NOMBRE VARCHAR(50) DEFAULT NULL,
  NIT VARCHAR(50) DEFAULT NULL,
  ESTADO VARCHAR(50) DEFAULT NULL,
  CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)  USING BTREE
);

CREATE TABLE IF NOT EXISTS TIPOLOGIAS_CUPOS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS CLASIFICACIONES_CUPOS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS PERIODICIDAD_INTERESES (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS TIPOS_CREDITO (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS AMORTIZACIONES_CAPITAL (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS TIPOS_ARCHIVOS_NEGOCIO (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 CODIGO VARCHAR(350) NOT NULL,
 NOMBRE VARCHAR(350) NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE
);

CREATE TABLE IF NOT EXISTS TERCEROS (
 ID INT NOT NULL AUTO_INCREMENT,
 NOMBRE VARCHAR(500) NOT NULL,
 IDENTIFICACION VARCHAR(50) NOT NULL,
 ID_CONTRIBUYENTE VARCHAR(50) NOT NULL,
 TIPO_TERCERO_ID INT UNSIGNED NOT NULL,
 TIPO_ORGANICACION_FISCAL_ID INT UNSIGNED NOT NULL,
 BANCO_ID INT UNSIGNED NOT NULL,
 TIPO_CUENTA_ID INT UNSIGNED NOT NULL,
 GRUPO_RETENCION_IMPUESTOS_ID INT UNSIGNED NOT NULL,
 CLASIFICACION_FISCAL_ID INT UNSIGNED NOT NULL,
 TIPO_CLASIFICACION_FISCAL_ID INT UNSIGNED NOT NULL,
 CLASIFICACION_IMPUESTOS_ID INT UNSIGNED NOT NULL,
 NUMERO_CUENTA VARCHAR(50) DEFAULT NULL,
 ESTADO VARCHAR(50) DEFAULT NULL,
 RETENCION_IMPUESTOS VARCHAR(1) DEFAULT NULL,
 CREADO TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID),
 KEY FK__TIPO_TERCERO (TIPO_TERCERO_ID),
 KEY FK__TIPO_ORGANIZACION_FISCAL (TIPO_ORGANICACION_FISCAL_ID),
 KEY FK__BANCOS (BANCO_ID),
 KEY FK__TIPO_CUENTAS (TIPO_CUENTA_ID),
 KEY FK__GRUPOS_RETENCIONES_IMPUESTOS (GRUPO_RETENCION_IMPUESTOS_ID),
 KEY FK__CLASIFICACIONES_FISCALES (CLASIFICACION_FISCAL_ID),
 KEY FK__TIPOS_CLASIFICACIONES_FISCALES (TIPO_CLASIFICACION_FISCAL_ID),
 KEY FK_TERCEROS_CODIGO_CLASIFICACIONES_IMPUESTOS (CLASIFICACION_IMPUESTOS_ID),
 CONSTRAINT FK__BANCOS FOREIGN KEY (BANCO_ID) REFERENCES BANCOS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK__CLASIFICACIONES_FISCALES FOREIGN KEY (CLASIFICACION_FISCAL_ID) REFERENCES CLASIFICACIONES_FISCALES (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK__GRUPOS_RETENCIONES_IMPUESTOS FOREIGN KEY (GRUPO_RETENCION_IMPUESTOS_ID) REFERENCES GRUPOS_RETENCIONES_IMPUESTOS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK__TIPO_CUENTAS FOREIGN KEY (TIPO_CUENTA_ID) REFERENCES TIPO_CUENTAS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK__TIPO_ORGANIZACION_FISCAL FOREIGN KEY (TIPO_ORGANICACION_FISCAL_ID) REFERENCES TIPO_ORGANIZACIONES_FISCALES (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK__TIPO_TERCERO FOREIGN KEY (TIPO_TERCERO_ID) REFERENCES TIPO_TERCEROS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK__TIPOS_CLASIFICACIONES_FISCALES FOREIGN KEY (TIPO_CLASIFICACION_FISCAL_ID) REFERENCES TIPOS_CLASIFICACIONES_FISCALES (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_TERCEROS_CLASIFICACIONES_IMPUESTOS FOREIGN KEY (CLASIFICACION_IMPUESTOS_ID) REFERENCES CLASIFICACIONES_IMPUESTOS (ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PERIODOS_TASAS (
 ID INT NOT NULL AUTO_INCREMENT,
 TASA_ID INT UNSIGNED NOT NULL,
 VALOR VARCHAR(50) NOT NULL,
 FECHA_INICIO DATE NOT NULL,
 FECHA_FINAL DATE NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID),
 KEY FK__TASAS (TASA_ID),
 CONSTRAINT FK__TASAS FOREIGN KEY (TASA_ID) REFERENCES TASAS (ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CUPOS (
 ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
 TIPOLOGIA_CUPO_ID INT UNSIGNED NOT NULL,
 CLASIFICACION_CUPO_ID INT UNSIGNED NOT NULL,
 UNIDAD_NEGOCIO_ID INT UNSIGNED NOT NULL,
 PROYECTO_ID INT UNSIGNED NOT NULL,
 BANCO_ID INT UNSIGNED NOT NULL,
 TIPO_CREDITO_ID INT UNSIGNED NOT NULL,
 AMORTIZACION_CAPITAL_ID INT UNSIGNED NOT NULL,
 PERIODICIDAD_INTERES_ID INT UNSIGNED NOT NULL,
 FEE_ID INT UNSIGNED NOT NULL,
 CUPO_APROBADO VARCHAR(350) NOT NULL,
 CUPO_DISPONIBLE VARCHAR(350) NOT NULL,
 CUPO_UTILIZADO VARCHAR(350) NOT NULL,
 CUPO_DISPONIBLE_CONSTRUCTOR VARCHAR(350) NOT NULL,
 FECHA_APROBACION_CUPO DATE NOT NULL,
 FECHA_VENCIMIENTO_CUPO DATE NOT NULL,
 PLAZO INT NOT NULL,
 CREADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ACTUALIZADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (ID) USING BTREE,
 CONSTRAINT FK_TIPOLOGIA_CUPO_ID FOREIGN KEY (TIPOLOGIA_CUPO_ID) REFERENCES TIPOLOGIAS_CUPOS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_CLASIFICACION_CUPO_ID FOREIGN KEY (CLASIFICACION_CUPO_ID) REFERENCES CLASIFICACIONES_CUPOS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_UNIDAD_NEGOCIO_ID FOREIGN KEY (UNIDAD_NEGOCIO_ID) REFERENCES UNIDADES_NEGOCIO (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_PROYECTO_ID FOREIGN KEY (PROYECTO_ID) REFERENCES PROYECTOS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_BANCO_ID FOREIGN KEY (BANCO_ID) REFERENCES BANCOS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_TIPO_CREDITO_ID FOREIGN KEY (TIPO_CREDITO_ID) REFERENCES TIPOS_CREDITO (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_AMORTIZACION_CAPITAL_ID FOREIGN KEY (AMORTIZACION_CAPITAL_ID) REFERENCES AMORTIZACIONES_CAPITAL (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_PERIODICIDAD_INTERES_ID FOREIGN KEY (PERIODICIDAD_INTERES_ID) REFERENCES PERIODICIDAD_INTERESES (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT FK_FEE_ID FOREIGN KEY (FEE_ID) REFERENCES TASAS (ID) ON DELETE RESTRICT ON UPDATE CASCADE
);